version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rahasia
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=lms_db
      - DB_USER=admin
      - DB_PASS=rahasia
      - DB_HOST=db
      - DB_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db